# Generated by Django 5.2.3 on 2025-07-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('standerd', models.CharField(max_length=50)),
            ],
        ),
    ]
